<?php 

$ket_vocab = array(
    "able (adj)",
    "about (adv & prep)",
    "above (adv & prep)",
    "accident (n)",
    "across (adv & prep)",
    "act (n & v)",
    "activity (n)",
    "actor (n)",
    "actually (adv)",
    "ad (n)",
    "add (v)",
    "address (n)",
    "adult (adj & n)",
    "advanced (adj)",
    "adventure (n)",
    "advertisement (n)",
    "advice (n)",
    "aeroplane (n)",
    "afraid (adj)",
    "after (adv & prep)",
    "afternoon (n)",
    "afterwards (adv)",
    "again (adv)",
    "against (prep)",
    "age (n)",
    "aged (adj)",
    "ago (adv)",
    "agree (v)",
    "air (n)",
    "airport (n)",
    "alarm clock (n)",
    "album (n)",
    "all (adv, det & pron)",
    "all right/alright (adj, adv & exclam)",
    "almost (adv)",
    "alone (adj & adv)",
    "along (prep)",
    "already (adv)",
    "alright (adj, adv & exclam)",
    "also (adv)",
    "always (adv)",
    "a.m. (adv)",
    "amazing (adj)",
    "ambulance (n)",
    "among (prep)",
    "and (conj)",
    "angry (adj)",
    "animal (n)",
    "another (det & pron)",
    "answer (n & v)",
    "any (det & pron)",
    "anybody (pron)",
    "anymore (adv)",
    "anyone (pron)",
    "anything (pron)",
    "anyway (adv)",
    "anywhere (adv)",
    "apartment (n)",
    "apartment building (n)",
    "apple (n)",
    "appointment (n)",
    "area (n)",
    "arm (n)",
    "armchair (n)",
    "around (adv & prep)",
    "arrive (v)",
    "art (n)",
    "article (n)",
    "artist (n)",
    "as (conj & prep)",
    "ask (v)",
    "assistant (n)",
    "as well (adv)",
    "as well (as) (prep)",
    "at (prep)",
    "attractive (adj)",
    "aunt (n)",
    "autumn (n)",
    "available (adj)",
    "away (adv)",
    "awful (adj)",
    "baby (n)",
    "back (n, adv & adj)",
    "backpack (n)",
    "bad (adj)",
    "badly (adv)",
    "badminton (n)",
    "bag (n)",
    "bake (v)",
    "ball (n)",
    "balloon (n)",
    "banana (n)",
    "band (n)",
    "bandage (n)",
    "bank (n)",
    "barbecue (n)",
    "baseball (n)",
    "basketball (n)",
    "bat (n)",
    "bath (n)",
    "bathing suit (n)",
    "bathroom (n)",
    "bathtub (n)",
    "battery (n)",
    "be (av & v)",
    "beach (n)",
    "bean (n)",
    "bear (n)",
    "beard (n)",
    "beautiful (adj)",
    "because (conj)",
    "become (v)",
    "bed (n)",
    "bedroom (n)",
    "bee (n)",
    "before (adv, conj & prep)",
    "begin (v)",
    "beginner (n)",
    "beginning (n)",
    "behind (adv & prep)",
    "believe (v)",
    "belong (v)",
    "below (adv & prep)",
    "belt (n)",
    "beside (prep)",
    "best (adj & adv)",
    "better (adj & adv)",
    "between (prep)",
    "bicycle (n)",
    "big (adj)",
    "bike (n)",
    "bill (n)",
    "biology (n)",
    "bird (n)",
    "birth (n)",
    "birthday (n)",
    "biscuit (n) (Br Eng) (Am Eng: cookie)",
    "bit (n)",
    "black (adj & n)",
    "blackboard (n)",
    "blanket (n)",
    "block (n)",
    "blond(e) (adj)",
    "blood (n)",
    "blouse (n)",
    "blue (adj & n)",
    "board (n)",
    "board game (n)",
    "boat (n)",
    "body (n)",
    "boil (v)",
    "boiled (adj)",
    "book (n & v)",
    "bookcase (n)",
    "bookshelf (n)",
    "bookshop (n) (Br Eng) (Am Eng: bookstore)",
    "bookstore (n) (Am Eng) (Br Eng: bookshop)",
    "boot (n)",
    "bored (adj)",
    "boring (adj)",
    "born (v)",
    "borrow (v)",
    "boss (n)",
    "both (pron & det)",
    "bother (v)",
    "bottle (n)",
    "bottom (n)",
    "bowl (n)",
    "box (n)",
    "boy (n)",
    "boyfriend (n)",
    "brain (n)",
    "brave (adj)",
    "bread (n)",
    "break (n & v)",
    "breakfast (n)",
    "bridge (n) ",
    "bright (adj)",
    "brilliant (adj)",
    "bring (v)",
    "broken (adj)",
    "brother (n)",
    "brown (adj & n)",
    "brush (n & v)",
    "build (v)",
    "building (n)",
    "burger (n)",
    "bus (n)",
    "business (n)",
    "businessman (n)",
    "businesswoman (n)",
    "bus station (n)",
    "bus stop (n)",
    "busy (adj)",
    "but (conj)",
    "butter (n)",
    "buy (v)",
    "by (prep)",
    "bye (exclam)",
    "cabinet (n)",
    "cafe/café (n)",
    "cafeteria (n)",
    "cake (n)",
    "calendar (n)",
    "call (n & v)",
    "camel",
    "camera (n)",
    "camp (v)",
    "camping (n)",
    "campsite (n)",
    "cap (n)",
    "capital (n)",
    "can (n & mv)",
    "candy (n)",
    "cannot (mv)",
    "car (n)",
    "card (n)",
    "career (n)",
    "careful (adj)",
    "carefully (adv)",
    "car park (n) (Br Eng) (Am Eng: parking lot)",
    "carpet (n)",
    "carrot (n)",
    "carry (v)",
    "cartoon (n)",
    "case (n)",
    "cash (n & v)",
    "castle (n)",
    "cat (n)",
    "catch (v)",
    "cathedral (n)",
    "CD (n)",
    "CD player (n)",
    "ceiling (n)",
    "cell phone (n)",
    "cent (n)",
    "centre/center (n)",
    "centimetre/centimeter (cm) (n)",
    "century (n)",
    "cereal (n)",
    "certainly (not) (adv)",
    "chain (n)",
    "chair (n)",
    "change (v & n)",
    "channel (n)",
    "chat (n)",
    "chatroom (n)",
    "cheap (adj)",
    "check (v)",
    "cheese (n)",
    "chef (n)",
    "chemist (n) (Br Eng) (Am Eng: drugstore)",
    "chemistry (n)",
    "cheque (n)",
    "chess (n)",
    "chicken (n)",
    "child (n)",
    "chilli (n)",
    "chips (n pl)",
    "chocolate (n)",
    "choose (v)",
    "cinema (n)",
    "circle (n)",
    "circus (n)",
    "city (n)",
    "class (n)",
    "classical (adj)",
    "classmate (n)",
    "classroom (n)",
    "clean (adj & v)",
    "cleaner (n)",
    "clear (adj)",
    "clearly (adv)",
    "clever (adj)",
    "click (n & v)",
    "climb (v)",
    "climbing (n)",
    "clock (n)",
    "close (adj & v)",
    "close to (prep phr)",
    "closed (adj)",
    "clothes (n pl)",
    "cloud (n)",
    "cloudy (adj)",
    "clown (n)",
    "club (n)",
    "coach (n)",
    "coat (n)",
    "coffee (n)",
    "cola (n)",
    "cold (adj & n)",
    "colleague (n)",
    "collect (v)",
    "college (n)",
    "colour (n & v)",
    "comb (n)",
    "come (v)",
    "comfortable (adj)",
    "comic (n)",
    "company (n)",
    "competition (n)",
    "complete (v)",
    "computer (n)",
    "concert (n)",
    "congratulations! (exclam)",
    "contact (n & v)",
    "conversation (n)",
    "cook (n & v)",
    "cooker (n)",
    "cookie (n) (Am Eng) (Br Eng: biscuit)",
    "cooking (n)",
    "cool (adj & exclam)",
    "copy (v)",
    "corner (n)",
    "correct (adj)",
    "cost (n & v)",
    "costume (n)",
    "could (mv)",
    "country (n)",
    "countryside (n)",
    "course (n)",
    "cousin (n)",
    "cover (v)",
    "cow (n)",
    "crazy (adj)",
    "cream (adj & n)",
    "credit card (n)",
    "cricket (n)",
    "cross (n & v)",
    "crossing (n)",
    "crowd (n)",
    "crowded (adj)",
    "cry (v)",
    "cup (n)",
    "cupboard (n)",
    "curry (n)",
    "curtain (n)",
    "customer (n)",
    "cut (v)",
    "cycle (v)",
    "cycling (n)",
    "dad (n)",
    "daily (adj & adv)",
    "dance (n & v)",
    "dancer (n)",
    "dancing (n)",
    "danger (n)",
    "dangerous (adj)",
    "dark (adj)",
    "date (n)",
    "daughter (n)",
    "day (n)",
    "dead (adj)",
    "dear (adj)",
    "decide (v)",
    "deep (adj)",
    "degree (n)",
    "delay (n & v)",
    "dentist (n)",
    "department (n) ",
    "department store (n)",
    "describe (v)",
    "desert (n)",
    "desk (n)",
    "dessert (n)",
    "detail (n)",
    "diary (n)",
    "dictionary (n)",
    "die (v)",
    "difference (n)",
    "different (adj)",
    "difficult (adj)",
    "digital (adj)",
    "digital camera (n)",
    "dining room (n)",
    "dinner (n)",
    "dinosaur (n)",
    "diploma (n)",
    "dirty (adj)",
    "disco (n)",
    "discount (n)",
    "discuss (v)",
    "dish (n)",
    "do (av & v)",
    "doctor (n)",
    "document (n)",
    "dog (n)",
    "doll (n)",
    "dollar (n)",
    "dolphin (n)",
    "door (n)",
    "dot (n)",
    "double (adj)",
    "down (adv & prep)",
    "download (n & v)",
    "internet (v).",
    "downstairs (adv)",
    "Dr (n)",
    "draw (v)",
    "drawer (n)",
    "drawing (n)",
    "dream (n & v)",
    "dress (n & v)",
    "dressed (adj)",
    "drink (n & v)",
    "drive (v)",
    "driver (n)",
    "driving licence (n)",
    "drugstore (n) (Am Eng) (Br Eng: chemist)",
    "drum (n)",
    "dry (adj & v)",
    "duck (n)",
    "during (prep)",
    "DVD (n)",
    "DVD player (n)",
    "each (det & pron)",
    "ear (n)",
    "early (adj & adv)",
    "earn (v)",
    "earring (n)",
    "easily (adv)",
    "east (n, adj & adv)",
    "easy (adj)",
    "eat (v)",
    "egg (n)",
    "electric (adj)",
    "electricity (n)",
    "elephant (n)",
    "elevator (n) (Am Eng) (Br Eng: lift)",
    "else (adv)",
    "email (n & v)",
    "empty (adj)",
    "end (v & n)",
    "engine (n)",
    "engineer (n)",
    "enjoy (v)",
    "enough (adv, det & pron)",
    "enter (v)",
    " competition?",
    "entrance (n)",
    "envelope (n)",
    "eraser (n) (Am Eng) (Br Eng: rubber)",
    "especially (adv)",
    "euro (n)",
    "even (adv)",
    "evening (n)",
    "ever (adv)",
    "every (det)",
    "everybody (pron)",
    "everyone (pron)",
    "everything (pron)",
    "everywhere (adv)",
    "exactly (adv)",
    "examination/exam (n)",
    "example (n)",
    "excellent (adj)",
    "except (conj & prep)",
    "excited (adj)",
    "exciting (adj) ",
    "excuse (v)",
    "exercise (n & v)",
    "exhibition (n)",
    "exit (n)",
    "expensive (adj)",
    "explain (v)",
    "explore (v)",
    "explorer (n)",
    "extra (adj)",
    "eye (n)",
    "face (n)",
    "fact (n)",
    "factory (n)",
    "fail (v)",
    "fair (adj)",
    "fall (n & v)",
    "family (n)",
    "famous (adj)",
    "fan (n)",
    "fantastic (adj)",
    "far (adv)",
    "farm (n)",
    "farmer (n)",
    "fashion (n)",
    "fast (adj & adv)",
    "fast food (n)",
    "fat (adj)",
    "father (n)",
    "favourite (adj)",
    "feel (v)",
    "festival (n)",
    "few (det & adj)",
    "field (n)",
    "file (n)",
    "fill (v)",
    "fill in (phr v)",
    "film (n & v)",
    "final (adj)",
    "finally (adv)",
    "find (v)",
    "find out (phr v)",
    "fine (adj)",
    "finger (n)",
    "finish (v)",
    "fire (n)",
    "first (adv & adj)",
    "first name (n)",
    "fish (n & v)",
    "fishing (n)",
    "fit (adj)",
    "flat (n)",
    "flight (n)",
    "floor (n)",
    "flower (n)",
    "fly (v)",
    "fog (n)",
    "foggy (adj)",
    "follow (v)",
    "food (n)",
    "foot (n)",
    "football (n)",
    "footballer (n)",
    "for (prep)",
    "foreign (adj)",
    "forest (n)",
    "forget (v)",
    "fork (n)",
    "form (n)",
    "free (adj & adv)",
    "French fries (n) (Am Eng) (Br Eng: chips)",
    "fresh (adj)",
    "fridge (n)",
    "fried (adj)",
    "friend (n)",
    "friendly (adj)",
    "from (prep)",
    "front (n)",
    "fruit (n)",
    "full (adj)",
    "fun (adj & n)",
    "funny (adj)",
    "furniture (n) ",
    "further (adj)",
    "future (n)",
    "game (n)",
    "garage (n)",
    "garden (n)",
    "garlic (n)",
    "gas (n) (Am Eng) (Br Eng: petrol)",
    "gas station (n) (Am Eng) (Br Eng: petrol station)",
    "gate (n)",
    "geography (n)",
    "get (v)",
    "get fit (v)",
    "get off (phr v)",
    "get on (phr v)",
    "get up (phr v)",
    "gift (n)",
    "girl (n)",
    "girlfriend (n)",
    "give (v)",
    "glad (adj)",
    "glass (n)",
    "glasses (n pl)",
    "glove (n)",
    "go (v)",
    "goal (n)",
    "gold (n & adj)",
    "golden (adj)",
    "golf (n)",
    "good (adj)",
    "good afternoon (exclam)",
    "goodbye (exclam)",
    "good evening (exclam)",
    "good-looking (adj)",
    "good morning (exclam)",
    "good night (exclam)",
    "go out (phr v)",
    "grade (n)",
    "gram(me) (n)",
    "grandchild (n)",
    "grand(d)ad (n)",
    "granddaughter (n)",
    "grandfather (n)",
    "grandma (n)",
    "grandmother (n)",
    "grandpa (n)",
    "grandparent (n)",
    "grandson (n)",
    "granny (n)",
    "grape (n)",
    "grass (n)",
    "great (adj)",
    "green (adj)",
    "grey (adj & n) (Br Eng) (Am Eng: gray)",
    "grilled (adj)",
    "grocery store (n) (Am Eng)",
    "group (n)",
    "grow (v)",
    "grow up (phr v)",
    "guess (v)",
    "guest (n)",
    "guest-house (n)",
    "guide (n)",
    "guidebook (n)",
    "guitar (n)",
    "guy (n)",
    "gym (n)",
    "hair (n)",
    "half (det, n & pron)",
    "half-price (adj)",
    "hall (n)",
    "hand (n)",
    "handbag (n)",
    "happen (v)",
    "happy (adj)",
    "hard (adj & adv)",
    "hat (n)",
    "hate (v)",
    "have (av & v)",
    "have got to (mv)",
    "have to (mv)",
    "he (pron)",
    "head (n)",
    "headache (n)",
    "headteacher (n)",
    "health (n)",
    "healthy (adj)",
    "hear (v)",
    "heart (n)",
    "heating (n)",
    "heavy (adj)",
    "helicopter (n)",
    "hello (exclam)",
    "help (v)",
    "her (det & pron)",
    "here (adv)",
    "hers (pron)",
    "herself (pron)",
    "hey (exclam)",
    "hi (exclam)",
    "high (adj)",
    "hill (n)",
    "him (pron)",
    "himself (pron)",
    "hip hop (n)",
    "his (det & pron)",
    "history (n)",
    "hit (v)",
    "hobby (n)",
    "hockey (n)",
    "hold (v)",
    "holiday (n)",
    "home (n & adv)",
    "homework (n)",
    "honey (n)",
    "hope (v)",
    "horrible (adj)",
    "horse (n)",
    "hospital (n)",
    "hot (adj)",
    "hotel (n)",
    "hour (n)",
    "house (n)",
    "housewife (n)",
    "how (adv)",
    "however (adv)",
    "hungry (adj)",
    "hurry (v)",
    "hurt (v)",
    "husband (n)",
    "I (pron)",
    "ice (n)",
    "ice cream (n)",
    "ice skating (n)",
    "ID (n)",
    "ID card (n)",
    "idea (n)",
    "identification (n)",
    "if (conj)",
    "ill (adj)",
    "immediately (adv)",
    "important (adj)",
    "improve (v)",
    "in (adv & prep)",
    "include (v)",
    "including (prep)",
    "indoor (adj)",
    "indoors (adv)",
    "information (n)",
    "in front of (prep phr)",
    "insect (n)",
    "inside (adv & prep)",
    "instead (adv)",
    "instructions (n pl)",
    "instrument (n)",
    "interested (adj)",
    "interesting (adj)",
    "international (adj)",
    "internet (n)",
    "into (prep)",
    "invitation (n)",
    "invite (v)",
    "island (n)",
    "it (pron)",
    "IT (n)",
    "its (det)",
    "itself (pron)",
    "jacket (n)",
    "jam (n)",
    "jazz (n)",
    "jeans (n pl)",
    "jewellery (n) (Br Eng) (Am Eng: jewelry)",
    "job (n)",
    "join (v)",
    "journalist (n)",
    "journey (n)",
    "juice (n)",
    "jump (v)",
    "jumper (n)",
    "just (adv)",
    "keep (v)",
    "key (n)",
    "keyboard (n)",
    "kick (n & v)",
    "kilogramme (kg) (n) (Br Eng) (Am Eng: kilogram)",
    "kilometre (km) (n) (Br Eng) (Am Eng: kilometer)",
    "kind (adj & n)",
    "king (n)",
    "kiss (n & v)",
    "kit (n)",
    "kitchen (n)",
    "kite (n)",
    "knife (n)",
    "know (v)",
    "lake (n)",
    "lamp (n)",
    "language (n)",
    "laptop (computer) (n)",
    "large (adj)",
    "last (adj & det)",
    "late (adv & adj)",
    "later (adv)",
    "latest (adj)",
    "laugh (v)",
    "lazy (adj)",
    "learn (v)",
    "least (adv)",
    "leather (n & adj)",
    "leave (v)",
    "left (adj, adv & n)",
    "left-hand (adj)",
    "leg (n)",
    "lemon (n)",
    "lemonade (n)",
    "lend (v)",
    "less (adj, det & pron)",
    "lesson (n)",
    "let (v)",
    "letter (n)",
    "level (n)",
    "library (n)",
    "licence (n)",
    "lie down (phr v)",
    "life (n)",
    "lift (n)",
    "light (n & adj)",
    "like (adv, prep & v)",
    "line (n)",
    "lion (n)",
    "list (n)",
    "listen (v)",
    "litre (n) (Br Eng) (Am Eng: liter)",
    "little (adj)",
    "live (v)",
    "living room (n)",
    "long (adj)",
    "look (v)",
    "look after (phr v)",
    "look at (phr v)",
    "look for (phr v)",
    "look out (phr v)",
    "lorry (n)",
    "lose (v)",
    "lost (adj)",
    "lots / a lot (n)",
    "loud (adj)",
    "love (n & v)",
    "lovely (adj)",
    "low (adj)",
    "luck (n)",
    "lucky (adj)",
    "luggage (n)",
    "lunch (n)",
    "lunchtime (n)",
    "machine (n)",
    "mad (adj)",
    "magazine (n)",
    "mail (n)",
    "main course (n)",
    "make (v)",
    "make-up (n)",
    "man (n)",
    "manager (n)",
    "mango (n)",
    "many (det & pron)",
    "map (n)",
    "mark (n)",
    "market (n)",
    "married (adj)",
    "match (n)",
    "maths/mathematics (n) (Br Eng)",
    "(Am Eng: math)",
    "matter (n & v)",
    "may (mv)",
    "maybe (adv)",
    "me (pron)",
    "meal (n)",
    "mean (v)",
    "meat (n)",
    "mechanic (n)",
    "medicine (n)",
    "meet (v)",
    "meeting (n)",
    "melon (n)",
    "member (n)",
    "memory (n)",
    "menu (n)",
    "message (n)",
    "metre (n) (Br Eng) (Am Eng: meter)",
    "midday (n)",
    "middle (n)",
    "midnight (n)",
    "might (mv)",
    "mile (n)",
    "milk (n)",
    "million (n)",
    "mind (v)",
    "mine (pron)",
    "mineral water (n)",
    "minus (prep)",
    "minute (n)",
    "mirror (n)",
    "Miss (n)",
    "miss (v)",
    "missing (adj)",
    "mistake (n)",
    "mix (v)",
    "mobile (phone) (n)",
    "model (n)",
    "modern (adj)",
    "moment (n)",
    "money (n)",
    "monkey (n)",
    "month (n)",
    "monthly (adj & adv)",
    "moon (n)",
    "more (adj, adv, det & pron)",
    "morning (n)",
    "most (adj, adv, det & pron)",
    "mother (n)",
    "motorbike (n)",
    "motorway (n)",
    "mountain (n)",
    "mouse (n)",
    "mouth (n)",
    "move (v)",
    "movie (n) (Am Eng) (Br Eng: film)",
    "movie theater (n) (Am Eng) (Br Eng: cinema)",
    "movie star (n) (Am Eng) (Br Eng: film star)",
    "MP3 player (n)",
    "Mr (n)",
    "Mrs (n)",
    "Ms (n)",
    "much (adj, adv, det & pron)",
    "mug (n)",
    "mum (n)",
    "museum (n)",
    "mushroom (n)",
    "music (n)",
    "musical (adj)",
    "musician (n)",
    "must (mv)",
    "my (det)",
    "myself (pron)",
    "name (n)",
    "national (adj)",
    "nationality (n)",
    "nature (n)",
    "near (adv & prep)",
    "nearly (adv)",
    "neck (n)",
    "necklace (n)",
    "need (v)",
    "neighbour (n)",
    "net (n)",
    "never (adv)",
    "new (adj)",
    "news (n)",
    "newspaper (n)",
    "next (adj & adv)",
    "next to (prep)",
    "nice (adj)",
    "night (n)",
    "no (adv, det & pron)",
    "nobody (pron)",
    "noise (n)",
    "noisy (adj)",
    "noon (n)",
    "no one (pron)",
    "normal (adj)",
    "north (n, adj & adv)",
    "nose (n)",
    "not (adv)",
    "note (n & v)",
    "notebook (n)",
    "nothing (pron)",
    "notice (n)",
    "now (adv)",
    "number (n)",
    "nurse (n)",
    "occupation (n)",
    "o'clock (adv)",
    "of (prep)",
    "of course (not) (adv)",
    "off (adv)",
    "offer (n & v)",
    "office (n)",
    "often (adv)",
    "oh (exclam)",
    "oil (n)",
    "OK/okay (exclam)",
    "old (adj)",
    "omelette (n)",
    "on (prep & adv)",
    "once (adv)",
    "one (det & pron)",
    "onion (n)",
    "online (adj & adv)",
    "only (adv & adj)",
    "open (adj & v)",
    "opera (n)",
    "opposite (prep)",
    "or (conj)",
    "orange (adj & n)",
    "order (n)",
    "other (det & pron)",
    "our (det)",
    "ours (pron)",
    "ourselves (pron)",
    "out (adv)",
    "outdoors (adv)",
    "out of (prep)",
    "outside (prep & adv)",
    "over (prep & adv)",
    "own (adj)",
    "pack (v)",
    "page (n)",
    "pain (n)",
    "paint (v & n)",
    "painter (n)",
    "painting (n)",
    "pale (adj)",
    "pair (n)",
    "paper (n & adj)",
    "pardon (exclam)",
    "parent (n)",
    "park (n & v)",
    "parking lot (n) (Am Eng) (Br Eng: car park)",
    "part (n)",
    "partner (n)",
    "party (n)",
    "pass (v)",
    "passenger (n)",
    "passport (n)",
    "past (prep)",
    "pasta (n)",
    "path (n)",
    "pay (v)",
    "PC (personal computer) (n)",
    "pear (n)",
    "pen (n)",
    "pence (n)",
    "pencil (n)",
    "pencil case (n) ",
    "penfriend (n)",
    "penny (n)",
    "people (n pl)",
    "pepper (n)",
    "per (prep)",
    "perfect (adj)",
    "perfume (n)",
    "perhaps (adv)",
    "person (n)",
    "pet (n)",
    "petrol (n)",
    "petrol station (n)",
    "pharmacy (n)",
    "phone (v & n)",
    "photo(graph) (n)",
    "photographer (n)",
    "photography (n)",
    "physics (n)",
    "piano (n)",
    "pick up (phr v)",
    "picnic (n)",
    "picture (n)",
    "piece (n)",
    "pillow (n)",
    "pilot (n)",
    "pink (adj)",
    "pity (n)",
    "pizza (n)",
    "place (n)",
    "plan (n & v)",
    "plane (n)",
    "plant (n)",
    "plastic (n & adj)",
    "plate (n)",
    "platform (n)",
    "play (v & n)",
    "player (n)",
    "playground (n)",
    "pleasant (adj)",
    "please (v & exclam)",
    "pleased (adj)",
    "plus (prep)",
    "p.m. (adv)",
    "pocket (n)",
    "point (v)",
    "police (n)",
    "police car (n)",
    "police officer (n)",
    "police station (n)",
    "polite (adj)",
    "pool (n)",
    "poor (adj)",
    "pop (n)",
    "popular (adj)",
    "possible (adj)",
    "possibly (adv)",
    "post (v & n)",
    "postcard (n)",
    "poster (n)",
    "post office (n)",
    "potato (n)",
    "pound (£) (n)",
    "practice (n) (Br Eng) (Am Eng: practise)",
    "practise (v)",
    "prefer (v)",
    "prepare (v)",
    "present (n)",
    "pretty (adj)",
    "price (n)",
    "print (v)",
    "printer (n)",
    "prize (n)",
    "probably (adv)",
    "problem (n)",
    "program (n)",
    "programme (n)",
    "project (n)",
    "pull (v)",
    "pupil (n)",
    "purple (adj)",
    "purse (n)",
    "push (v)",
    "put (v)",
    "put on (phr v)",
    "puzzle (n)",
    "quarter (n)",
    "queen (n)",
    "question (n)",
    "quick (adj)",
    "quickly (adv)",
    "quiet (adj)",
    "quite (adv)",
    "quiz (n)",
    "rabbit (n)",
    "race (n & v)",
    "racket (n)",
    "radio (n)",
    "railway (n)",
    "rain (n & v)",
    "raincoat (n)",
    "rap (n)",
    "read (v)",
    "reading (n)",
    "ready (adj)",
    "real (adj)",
    "really (adv)",
    "reason (n)",
    "receipt (n)",
    "receive (v)",
    "receptionist (n)",
    "record (v)",
    "red (adj)",
    "refrigerator (n)",
    "remember (v)",
    "rent (v)",
    "repair (v)",
    "repeat (v)",
    "rest (n & v)",
    "restaurant (n)",
    "return (n & v)",
    "rice (n)",
    "rich (adj)",
    "ride (n & v)",
    "right (n, adj & adv)",
    "right hand (adj)",
    "ring (n)",
    "river (n)",
    "road (n)",
    "roast (v & adj)",
    "rock (n)",
    "roof (n)",
    "room (n)",
    "round (adj)",
    "roundabout (n)",
    "rubber (n)",
    "rugby (n)",
    "ruler (n)",
    "run (v)",
    "runner (n)",
    "running (n)",
    "sad (adj)",
    "safe (adj)",
    "sail (v)",
    "sailing (n)",
    "salad (n)",
    "sale (n)",
    "salt (n)",
    "same (adj & pron)",
    "sandwich (n)",
    "sauce (n)",
    "sausage (n)",
    "save (v)",
    "say (v)",
    "scarf (n)",
    "school (n)",
    "schoolchild (n)",
    "science (n)",
    "scissors (n pl)",
    "scooter (n)",
    "screen (n)",
    "sea (n)",
    "seat (n)",
    "second (adj, det & n)",
    "secretary (n)",
    "see (v)",
    "sell (v)",
    "send (v)",
    "sentence (n)",
    "serve (v)",
    "set (n)",
    "several (det & pron)",
    "shall (mv)",
    "shame (n)",
    "shampoo (n & v)",
    "share (v)",
    "she (pron)",
    "sheep (n)",
    "sheet (n)",
    "shelf (n)",
    "ship (n)",
    "shirt (n)",
    "shoe (n)",
    "shop (n & v)",
    "shop assistant (n)",
    "shopping (n)",
    "short (adj)",
    "shorts (n pl)",
    "should (mv)",
    "shout (v)",
    "show (v & n)",
    "shower (n)",
    "shut (v)",
    "sick (adj)",
    "side (n)",
    "sightseeing (n)",
    "sign (n)",
    "silver (n & adj)",
    "simple (adj)",
    "since (prep)",
    "sing (v)",
    "singer (n)",
    "singing (n)",
    "single (adj)",
    "sink (n)",
    "sister (n)",
    "sit (v)",
    "sit down (phr v)",
    "site (n)",
    "sitting room (n)",
    "size (n)",
    "skate (v)",
    "skateboard (n)",
    "skateboarding (n)",
    "skating (n)",
    "ski (v)",
    "skiing (n)",
    "skirt (n)",
    "sky (n)",
    "sleep (v)",
    "slice (n)",
    "slim (adj)",
    "slow (adj)",
    "slowly (adv)",
    "small (adj)",
    "smoke (v)",
    "smoking (n)",
    "snack (n)",
    "snow (n & v)",
    "snowboard (n)",
    "snowboarding (n)",
    "so (conj & adv)",
    "soap (n)",
    "soccer (n)",
    "sock (n)",
    "sofa (n)",
    "soft (adj)",
    "software (n)",
    "some (det & pron)",
    "somebody (pron)",
    "someone (pron)",
    "something (pron)",
    "sometimes (adv)",
    "somewhere (adv)",
    "son (n)",
    "song (n)",
    "soon (adv)",
    "sorry (adj)",
    "sort (n)",
    "sound (v)",
    "soup (n)",
    "south (n, adj & adv)",
    "space (n)",
    "spare (adj)",
    "speak (v)",
    "speaker (n)",
    "special (adj)",
    "spell (v)",
    "spelling (n)",
    "spend (v)",
    "spoon (n)",
    "sport (n)",
    "sports centre (n)",
    "spring (n)",
    "square (n & adj)",
    "stadium (n)",
    "staff (n)",
    "stage (n)",
    "stairs (n pl)",
    "stamp (n)",
    "stand (v)",
    "star (n & v)",
    "start (v)",
    "station (n)",
    "stay (v)",
    "steak (n)",
    "steal (v)",
    "still (adv)",
    "stomach (n)",
    "stomach ache (n)",
    "stop (n & v)",
    "store (n)",
    "storm (n)",
    "story (n)",
    "straight (adj & adv)",
    "strange (adj)",
    "street (n)",
    "strong (adj)",
    "student (n)",
    "studies (n pl)",
    "study (v)",
    "subject (n)",
    "such (det)",
    "suddenly (adv)",
    "sugar (n)",
    "suit (n)",
    "suitcase (n)",
    "summer (n)",
    "sun (n)",
    "sunglasses (n pl)",
    "sunny (adj)",
    "supermarket (n)",
    "supper (n)",
    "suppose (v)",
    "sure (adj)",
    "surf (v)",
    "surfboard (n)",
    "surfing (n)",
    "surname (n)",
    "surprise (n)",
    "surprised (adj)",
    "sweater (n)",
    "sweet (n & adj)",
    "swim (v)",
    "swimming (n)",
    "swimming costume (n) (Br Eng) (Am Eng: bathing suit)",
    "swimming pool (n)",
    "swimsuit (n)",
    "table (n)",
    "table tennis (n)",
    "take (v)",
    "take off (phr v)",
    "talk (n & v)",
    "tall (adj)",
    "taxi (n)",
    "tea (n)",
    "teach (v)",
    "teacher (n)",
    "team (n)",
    "teenager (n)",
    "telephone (n & v)",
    "television (TV) (n)",
    "tell (v)",
    "temperature (n)",
    "tennis (n)",
    "tent (n)",
    "term (n)",
    "terrible (adj)",
    "test (n)",
    "text (n & v)",
    "textbook (n)",
    "text message (n)",
    "than (prep & conj)",
    "thank (v)",
    "thanks (exclam)",
    "thank you (exclam)",
    "that (conj & pron)",
    "the (det)",
    "theatre (n) (Br Eng) (Am Eng: theater)",
    "their (det)",
    "theirs (pron)",
    "them (pron)",
    "themselves (pron)",
    "then (adv)",
    "there (adv)",
    "these (det & pron)",
    "they (pron)",
    "thin (adj)",
    "thing (n)",
    "think (v)",
    "thirsty (adj)",
    "this (det & pron)",
    "those (det & pron)",
    "through (prep)",
    "throw (v)",
    "thunderstorm (n)",
    "ticket (n)",
    "tidy (adj & v)",
    "tidy up (v)",
    "tie (n)",
    "tiger (n)",
    "tights (n pl)",
    "till (prep)",
    "time (n)",
    "timetable (n)",
    "tired (adj)",
    "to (prep)",
    "toast (n)",
    "today (n & adv)",
    "toe (n)",
    "together (adv)",
    "toilet (n)",
    "tomato (n)",
    "tomorrow (n & adv)",
    "tonight (n & adv)",
    "too (adv)",
    "tooth (n)",
    "toothbrush (n)",
    "top (n)",
    "total (adj & n)",
    "tour (n)",
    "tour guide (n)",
    "tourist (n)",
    "tourist information centre (n)",
    "towel (n)",
    "town (n)",
    "toy (n)",
    "traffic (n)",
    "traffic light (n)",
    "train (n)",
    "trainer (n)",
    "tram (n)",
    "travel (v)",
    "tree (n)",
    "trip (n)",
    "trouble (n)",
    "trousers (n pl)",
    "true (adj)",
    "try (v)",
    "try on (phr v)",
    "T-shirt (n)",
    "turn (v)",
    "turn off (phr v)",
    "turn on (phr v)",
    "twice (adv)",
    "type (n)",
    "tyre (n) (Am Eng: tire)",
    "umbrella (n)",
    "uncle (n)",
    "under (prep)",
    "underground (n & adj)",
    "understand (v)",
    "unfortunately (adj)",
    "unhappy (n)",
    "uniform (n)",
    "university (n)",
    "until (prep)",
    "unusual (adj)",
    "up (prep & adv)",
    "upset (adj)",
    "upstairs (adv)",
    "us (pron)",
    "use (v)",
    "useful (adj)",
    "usual (adj)",
    "usually (adv)",
    "v/versus (prep)",
    "variety (n)",
    "various (adj)",
    "vegetable (n)",
    "very (adv)",
    "video (n)",
    "video game (n)",
    "view (n)",
    "village (n)",
    "violin (n)",
    "visit (v)",
    "visitor (n)",
    "vocabulary (n)",
    "volleyball (n)",
    "wait (v)",
    "waiter (n)",
    "waitress (n)",
    "wake (v)",
    "wake up (phr v)",
    "walk (v)",
    "walking (n)",
    "wall (n)",
    "wallet (n)",
    "want (v)",
    "warm (adj)",
    "wash (v)",
    "washing machine (n)",
    "washing-up (n)",
    "wash up (phr v)",
    "watch (n & v)",
    "water (n)",
    "way (n)",
    "we (pron)",
    "wear (v)",
    "weather (n)",
    "web (n)",
    "web page (n)",
    "website (n)",
    "week (n)",
    "weekday (n)",
    "weekend (n)",
    "weekly (adj & adv)",
    "welcome (adj & exclam)",
    "well (adv & adj)",
    "well known (adj)",
    "west (n, adj & adv)",
    "wet (adj)",
    "what (det & pron)",
    "wheel (n)",
    "when (adv)",
    "where (adv)",
    "which (det & pron)",
    "while (conj)",
    "white (adj)",
    "who (pron)",
    "whole (adj & n)",
    "why (adv)",
    "wide (adj)",
    "wife (n)",
    "wild (adj)",
    "will ('ll) (mv)",
    "win (v)",
    "wind (n)",
    "window (n)",
    "windsurfing (n)",
    "windy (adj)",
    "winner (n)",
    "winter (n)",
    "wish (n)",
    "with (prep)",
    "without (prep)",
    "woman (n)",
    "wonderful (adj)",
    "wood (n)",
    "wooden (adj)",
    "wool (n)",
    "word (n)",
    "work (n & v)",
    "worker (n)",
    "world (n)",
    "worried (adj)",
    "worry (v)",
    "worse (adj)",
    "worst (adj)",
    "would (mv)",
    "wow (exclam)",
    "write (v)",
    "write down (phr v)",
    "writer (n)",
    "writing (n)",
    "wrong (adj)",
    "yeah (exclam)",
    "year (n)",
    "yellow (adj)",
    "yes (adv)",
    "yesterday (adv)",
    "yet (adv)",
    "yog(h)urt (n)",
    "you (pron)",
    "young (adj)",
    "your (det)",
    "yours (pron)",
    "yourself (pron)",
    "zero (n)",
    "zoo (n)",
    );


 ?>